/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package html

import (
	"strings"
	"testing"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

func TestTextOf(t *testing.T) {
	cases := []struct {
		name string
		html string
		want string
	}{
		{"p", `<p data-v-f3ebc54b="" class="param-description">Aspect ratio of the generated images
                            (width:height)</p>`, "Aspect ratio of the generated images (width:height)\n"},
		{"codeBody", codeBody, `{
"code": 0, // Error codes; specific definitions see Error codes
"message": "string", // Error information
"request_id": "string", // Request ID, generated by the system, for tracking and troubleshooting
"data": {
"task_id": "string", // Task ID, generated by the system
"task_status": "string", // Task status: submitted, processing, succeed, failed
"task_info": { // Task creation parameters
  "external_task_id": "string" // Customer-defined task ID
},
"created_at": 1722769557708, // Task creation time, Unix timestamp, ms
"updated_at": 1722769557708 // Task update time, Unix timestamp, ms
}
}

`},
	}
	for _, c := range cases {
		doc, e := html.Parse(strings.NewReader(c.html))
		if e != nil {
			t.Fatalf("%s error: %v", c.name, e)
		}
		if got := textOf(doc, false, noFilter{}); got != c.want {
			t.Errorf("%s: `%s`, want `%s`", c.name, got, c.want)
		}
	}
}

const codeBody = `<div data-v-9ebd45a1="" class="code-body">
<pre data-v-9ebd45a1=""><code data-v-9ebd45a1="" class="hljs language-json"><span class="hljs-punctuation">{</span>
<span class="hljs-attr">"code"</span><span class="hljs-punctuation">:</span> <span class="hljs-number">0</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Error codes; specific definitions see Error codes</span>
<span class="hljs-attr">"message"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"string"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Error information</span>
<span class="hljs-attr">"request_id"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"string"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Request ID, generated by the system, for tracking and troubleshooting</span>
<span class="hljs-attr">"data"</span><span class="hljs-punctuation">:</span> <span class="hljs-punctuation">{</span>
<span class="hljs-attr">"task_id"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"string"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Task ID, generated by the system</span>
<span class="hljs-attr">"task_status"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"string"</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Task status: submitted, processing, succeed, failed</span>
<span class="hljs-attr">"task_info"</span><span class="hljs-punctuation">:</span> <span class="hljs-punctuation">{</span> <span class="hljs-comment">// Task creation parameters</span>
  <span class="hljs-attr">"external_task_id"</span><span class="hljs-punctuation">:</span> <span class="hljs-string">"string"</span> <span class="hljs-comment">// Customer-defined task ID</span>
<span class="hljs-punctuation">}</span><span class="hljs-punctuation">,</span>
<span class="hljs-attr">"created_at"</span><span class="hljs-punctuation">:</span> <span class="hljs-number">1722769557708</span><span class="hljs-punctuation">,</span> <span class="hljs-comment">// Task creation time, Unix timestamp, ms</span>
<span class="hljs-attr">"updated_at"</span><span class="hljs-punctuation">:</span> <span class="hljs-number">1722769557708</span> <span class="hljs-comment">// Task update time, Unix timestamp, ms</span>
<span class="hljs-punctuation">}</span>
<span class="hljs-punctuation">}</span></code></pre>
</div>`

type commentRemover struct{}

func (f commentRemover) Filter(node *html.Node) bool {
	if node.DataAtom != atom.Span {
		return true
	}
	for _, a := range node.Attr {
		if a.Key == "class" && a.Val == "hljs-comment" {
			return false
		}
	}
	return true
}

func TestTextFilter(t *testing.T) {
	cases := []struct {
		name string
		html string
		want string
	}{
		{"codeBody", codeBody, `{
"code": 0, 
"message": "string", 
"request_id": "string", 
"data": {
"task_id": "string", 
"task_status": "string", 
"task_info": { 
  "external_task_id": "string" 
},
"created_at": 1722769557708, 
"updated_at": 1722769557708 
}
}

`},
	}
	for _, c := range cases {
		doc, e := html.Parse(strings.NewReader(c.html))
		if e != nil {
			t.Fatalf("%s error: %v", c.name, e)
		}
		if got := textOf(doc, false, commentRemover{}); got != c.want {
			t.Errorf("%s: `%s`, want `%s`", c.name, got, c.want)
		}
	}
}
