// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"github.com/goplus/cobra/xcmd"
	"github.com/goplus/xgo/dql/fetcher"
	_ "github.com/goplus/xgo/dql/fetcher/github.com/issueTask"
	_ "github.com/goplus/xgo/dql/fetcher/github.com/repoList"
	_ "github.com/goplus/xgo/dql/fetcher/hrefs"
	_ "github.com/goplus/xgo/dql/fetcher/pkg.go.dev/importedBy"
	_ "github.com/goplus/xgo/dql/fetcher/pytorch.org/fndoc"
	"github.com/qiniu/x/errors"
	_ "github.com/qiniu/x/stream/http/cached"
	"io"
	"log"
	"os"
	"strings"
)

const _ = true

type Cmd_fetch struct {
	xcmd.Command
	*App
}
type Cmd_list struct {
	xcmd.Command
	*App
}
type App struct {
	xcmd.App
}
//line cmd/hdq/main_app.gox:26
func (this *App) MainEntry() {
//line cmd/hdq/main_app.gox:26:1
	this.Use("hdq")
//line cmd/hdq/main_app.gox:28:1
	this.Short("hdq - An HTML DOM Query Tool (powered by XGo DQL)")
}
func (this *App) Main() {
	_xgo_obj0 := &Cmd_fetch{App: this}
	_xgo_obj1 := &Cmd_list{App: this}
	xcmd.XGot_App_Main(this, _xgo_obj0, _xgo_obj1)
}
//line cmd/hdq/fetch_cmd.gox:24
func (this *Cmd_fetch) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/hdq/fetch_cmd.gox:24:1
	this.Use("fetch [flags] fetchType [input ... | -]")
//line cmd/hdq/fetch_cmd.gox:26:1
	this.Short("Fetch objects from the html source with the specified fetchType and inputs")
//line cmd/hdq/fetch_cmd.gox:28:1
	this.Run__1(func(args []string) {
//line cmd/hdq/fetch_cmd.gox:29:1
		if len(args) < 1 {
//line cmd/hdq/fetch_cmd.gox:30:1
			this.Help()
//line cmd/hdq/fetch_cmd.gox:31:1
			return
		}
//line cmd/hdq/fetch_cmd.gox:33:1
		fetchType := args[0]
//line cmd/hdq/fetch_cmd.gox:34:1
		inputs := args[1:]
//line cmd/hdq/fetch_cmd.gox:35:1
		if len(inputs) == 1 && inputs[0] == "-" {
//line cmd/hdq/fetch_cmd.gox:36:1
			inputs = strings.Fields(string(func() (_xgo_ret []byte) {
//line cmd/hdq/fetch_cmd.gox:36:1
				var _xgo_err error
//line cmd/hdq/fetch_cmd.gox:36:1
				_xgo_ret, _xgo_err = io.ReadAll(os.Stdin)
//line cmd/hdq/fetch_cmd.gox:36:1
				if _xgo_err != nil {
//line cmd/hdq/fetch_cmd.gox:36:1
					_xgo_err = errors.NewFrame(_xgo_err, "io.readAll(os.Stdin)", "cmd/hdq/fetch_cmd.gox", 36, "main.Main")
//line cmd/hdq/fetch_cmd.gox:36:1
					panic(_xgo_err)
				}
//line cmd/hdq/fetch_cmd.gox:36:1
				return
			}()))
		}
//line cmd/hdq/fetch_cmd.gox:38:1
		docs := make([]interface{}, 0, len(inputs))
		for
//line cmd/hdq/fetch_cmd.gox:39:1
		_, input := range inputs {
//line cmd/hdq/fetch_cmd.gox:40:1
			log.Println("==> Fetch", input)
//line cmd/hdq/fetch_cmd.gox:41:1
			doc := func() (_xgo_ret any) {
//line cmd/hdq/fetch_cmd.gox:41:1
				var _xgo_err error
//line cmd/hdq/fetch_cmd.gox:41:1
				_xgo_ret, _xgo_err = fetcher.Do(fetchType, input)
//line cmd/hdq/fetch_cmd.gox:41:1
				if _xgo_err != nil {
//line cmd/hdq/fetch_cmd.gox:41:1
					_xgo_err = errors.NewFrame(_xgo_err, "fetcher.do(fetchType, input)", "cmd/hdq/fetch_cmd.gox", 41, "main.Main")
//line cmd/hdq/fetch_cmd.gox:41:1
					panic(_xgo_err)
				}
//line cmd/hdq/fetch_cmd.gox:41:1
				return
			}()
//line cmd/hdq/fetch_cmd.gox:42:1
			docs = append(docs, doc)
		}
//line cmd/hdq/fetch_cmd.gox:44:1
		enc := json.NewEncoder(os.Stdout)
//line cmd/hdq/fetch_cmd.gox:45:1
		enc.SetIndent("", "  ")
//line cmd/hdq/fetch_cmd.gox:46:1
		func() {
//line cmd/hdq/fetch_cmd.gox:46:1
			var _xgo_err error
//line cmd/hdq/fetch_cmd.gox:46:1
			_xgo_err = enc.Encode(docs)
//line cmd/hdq/fetch_cmd.gox:46:1
			if _xgo_err != nil {
//line cmd/hdq/fetch_cmd.gox:46:1
				_xgo_err = errors.NewFrame(_xgo_err, "enc.encode docs", "cmd/hdq/fetch_cmd.gox", 46, "main.Main")
//line cmd/hdq/fetch_cmd.gox:46:1
				panic(_xgo_err)
			}
//line cmd/hdq/fetch_cmd.gox:46:1
			return
		}()
	})
}
func (this *Cmd_fetch) Classfname() string {
	return "fetch"
}
//line cmd/hdq/list_cmd.gox:20
func (this *Cmd_list) Main(_xgo_arg0 string) {
	this.Command.Main(_xgo_arg0)
//line cmd/hdq/list_cmd.gox:20:1
	this.Use("list")
//line cmd/hdq/list_cmd.gox:22:1
	this.Short("List all supported fetchTypes.")
//line cmd/hdq/list_cmd.gox:24:1
	this.Run__0(func() {
		for
//line cmd/hdq/list_cmd.gox:25:1
		_, ft := range fetcher.List() {
//line cmd/hdq/list_cmd.gox:26:1
			fmt.Println(ft)
		}
	})
}
func (this *Cmd_list) Classfname() string {
	return "list"
}
func main() {
	new(App).Main()
}
